name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: ecovision-faetec-apk
          path: bin/*.apk
